server:
  port: 9090
  tomcat:
    max-threads: 1000
    max-connections: 20000
    max-http-header-size: 655360
    max-http-post-size: -1
    uri-encoding: UTF-8
  servlet:
    context-path: /

logging:
#  config: https://fx32888.oss-cn-shenzhen.aliyuncs.com/test/log4j2_config/log4j2.xml

spring:
  application:
    name: fu-gateway-test
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

  cloud:
    gateway:
      routes:
        #netty 路由过滤器，http或https开头
        - id: baidu-route
          uri: https://www.baidu.com
          predicates:
            - Host=localhost:9090
          filters:
            - Slog=debug,001



